# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/inc/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/libcamera.so:obj/lib/libcamera.so

# All the blobs necessary for inc
PRODUCT_COPY_FILES += \
    vendor/motorola/triumph/proprietary/libcommondefs.so:/obj/lib/libcommondefs.so \
    vendor/motorola/triumph/proprietary/libcommondefs.so:/system/lib/libcommondefs.so \
    vendor/motorola/triumph/proprietary/wpa_supplicant:/system/bin/wpa_supplicant \
    vendor/motorola/triumph/proprietary/yamato_pfp.fw:/system/etc/firmware/yamato_pfp.fw \
    vendor/motorola/triumph/proprietary/yamato_pm4.fw:/system/etc/firmware/yamato_pm4.fw \
    vendor/motorola/triumph/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/motorola/triumph/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/motorola/triumph/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/motorola/triumph/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/motorola/triumph/proprietary/libOmxVdec.so:/system/lib/libOmxVdec.so \
    vendor/motorola/triumph/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/motorola/triumph/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/motorola/triumph/proprietary/libril.so:/system/lib/libril.so \
    vendor/motorola/triumph/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/motorola/triumph/proprietary/surf_keypad_qwerty.kcm.bin:/system/usr/keychars/surf_keypad_qwerty.kcm.bin \
    vendor/motorola/triumph/proprietary/surf_keypad.kl:/system/usr/keylayout/surf_keypad.kl \
    vendor/motorola/triumph/proprietary/fih_headsethook.kcm.bin:/system/usr/keychars/fih_headsethook.kcm.bin \
    vendor/motorola/triumph/proprietary/fih_headsethook.kl:/system/usr/keylayout/fih_headsethookd.kl
